In [5]:
#if you slice array you create view and it will change the value on original array.  
import numpy as np
a = np.array([23425, 27, 546, 215, -2154])

In [7]:
c = a.copy

In [12]:
a[2:4]

array([546, 215])

In [14]:
print(a)

[23425    27   546   215 -2154]


In [16]:
b = a[2:4]

In [17]:
b

array([546, 215])

In [18]:
a

array([23425,    27,   546,   215, -2154])

In [20]:
b[:] = 777

In [21]:
b

array([777, 777])

In [22]:
a

array([23425,    27,   777,   777, -2154])